### ISSUE TITLE
Not able to run install.bat file with visual studio March 2019 (Version 1.33)

### ISSUE THREAD

**Issue by YKUDACH** [qtronic/fmusdk#10]
Hello,
Not able to run the install.bat file , Ending up with following error 
1. No Microsoft Visual C compiler found ( Installed in system visual studio March 2019 (Version 1.33))
2. The system cannot find the path specified.'build_all' is not recognized as an internal or external command,operable program or batch file.
Kindly let me know any supporting tools required, to run the batch file 

Thankyou in advance

**Comment by adriantirea** [comment]
FMUSDK has two build scripts available for Windows. The install.bat and cmake.
1. Install.bat is limited up to Visual Studio 2015. It needs changes in the bat scripts to go up to VS 2019.
2. I do not see how build_all.bat is not recognized.


You could try cmake. I have just tried cmake with VS 2019 and it works.
