### ISSUE TITLE
Generated FMU 1.0 ME with zero states fails the FMU Checker 2.0.4

### ISSUE THREAD

**Issue by beutlich** [qtronic/fmusdk#6]
If the generated FMU 1.0 ME has zero states (as for example in https://github.com/qtronic/fmusdk/blob/6a3cdf017d12dd104cdd77bbbefbaf183b276a9f/fmu10/src/models/inc/inc.c#L15) it fails the FMU compliance checker 2.0.4 when calling fmiSetContinuousStates/fmiGetStateValueReferences/fmiGetContinuousStates/fmiGetNominalContinuousStates/fmiGetDerivatives with a NULL pointer as state vector.

```
[VERBOSE][FMICAPI] Calling fmiInitialize
	[FMU][log][FMU status:OK] fmiInitialize: toleranceControlled=0 relativeTolerance=0.0001
	[FMU][error][FMU status:Error] fmiGetContinuousStates: Invalid argument states[] = NULL.
[FATAL][FMUCHK] Failed to initialize FMU for simulation (FMU status: Error)
[FATAL][FMUCHK] Simulation loop terminated at time 0 since FMU returned status: Error
	[FMU][error][FMU status:Error] fmiTerminate: Illegal call sequence.
[ERROR][FMUCHK] fmiTerminate returned status: Error
```

[inc.zip](https://github.com/qtronic/fmusdk/files/6103505/inc.zip)

**Comment by adriantirea** [comment]
Thanks for issue report. Indeed there were the states related functions that did not permitted NULL vector argument.
The solution committed here is similar to the one for fmi2SetReal.

**Comment by beutlich** [comment]
Thanks. Please do not forget to also update the revision history in fmuTemplate.c, especially if the fix is related to a GitHub issue.
