### ISSUE TITLE
Example Command incorrect for Windows

### ISSUE THREAD

**Issue by egwood** [qtronic/fmusdk#7]
The command in the example omits a directory level.

The command as given:

   fmusim me10 fmu10/fmu/me/bouncingBall.fmu 5 0.1 0 s

For win32 it should be:

   fmusim me10 fmu10/fmu/me/win32/bouncingBall.fmu 5 0.1 0 s

**Comment by adriantirea** [comment]
Thanks for spotting the mistake.
