### ISSUE TITLE
64-bit build does not work for Windows w/MSVS 2017

### ISSUE THREAD

**Issue by egwood** [qtronic/fmusdk#8]
Not supporting MSVS 2017 for new users seems cruel:

-----------------------------------------------------------
Making the simulators and models for FMI 2.0 of the FmuSDK ...
-----------------------------------------------------------
building fmusim_me.exe - FMI for Model Exchange 2.0
-----------------------------------------------------------
The specified configuration type is missing.  The tools for the
configuration might not be installed.
main.c
sim_support.c
xmlVersionParser.c
Generating Code...
Compiling...
XmlParser.cpp
XmlElement.cpp
XmlParserCApi.cpp
Generating Code...
xmlVersionParser.obj : error LNK2019: unresolved external symbol _xmlFreeTextReader referenced in function _streamFile
XmlParser.obj : error LNK2001: unresolved external symbol _xmlFreeTextReader
xmlVersionParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderRead referenced in function _readNextInXml
XmlParser.obj : error LNK2001: unresolved external symbol _xmlTextReaderRead
xmlVersionParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderNodeType referenced in function _readNextInXml
XmlParser.obj : error LNK2001: unresolved external symbol _xmlTextReaderNodeType
xmlVersionParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderConstLocalName referenced in function _streamFile
XmlParser.obj : error LNK2001: unresolved external symbol _xmlTextReaderConstLocalName
xmlVersionParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderGetAttribute referenced in function _extractFmiVersionAttribute
xmlVersionParser.obj : error LNK2019: unresolved external symbol _xmlReaderForFile referenced in function _streamFile
XmlParser.obj : error LNK2001: unresolved external symbol _xmlReaderForFile
xmlVersionParser.obj : error LNK2019: unresolved external symbol _xmlFree referenced in function _extractFmiVersionAttribute
XmlParser.obj : error LNK2001: unresolved external symbol _xmlFree
XmlParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderDepth referenced in function __catch$?parseElementAttributes@XmlParser@@QAEXPAVElement@@_N@Z$0
XmlParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderIsEmptyElement referenced in function __catch$?parseElementAttributes@XmlParser@@QAEXPAVElement@@_N@Z$0
XmlParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderName referenced in function __catch$?parse@XmlParser@@QAEPAVModelDescription@@XZ$1
XmlParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderValue referenced in function __catch$?parse@XmlParser@@QAEPAVModelDescription@@XZ$1
XmlParser.obj : error LNK2019: unresolved external symbol _xmlTextReaderMoveToNextAttribute referenced in function __catch$?parse@XmlParser@@QAEPAVModelDescription@@XZ$1
..\shared\parser\win64\libxml2.lib : warning LNK4272: library machine type 'x64' conflicts with target machine type 'x86'
fmusim_me.exe : fatal error LNK1120: 12 unresolved externals
build of fmusim_me.exe failed
done.
-

**Comment by adriantirea** [comment]
FMUSDK has two build scripts available for Windows. The install.bat and cmake.
I suppose you used install.bat. Install.bat indeed is limited up to 2015. It needs updates up to VS 2019.

You could try cmake. I have just tried cmake with VS 2019 and it works.
